### ISSUE TITLE
How to specify a hasOne relation

### ISSUE THREAD

**Issue by cjroebuck** [ebryn/ember-model#262]
How would I simulate a hasOne relation? 

e.g. 
Course `hasOne` Venue
Course `hasOne` Tutor etc

Course: {
    "id": "1",
    "venue": "1",
    "tutor":"1",
}

Venue: {
   "id": "1",
   "title": "University"
}

**Comment by 1412** [comment]
its happen to me, what should i do to fix it?

**Comment by ivan-leschinsky** [comment]
@1412, use `belongsTo()`

**Comment by 1412** [comment]
can you elaborate please?, 
also please note thats its seems my problem is its deep chain relation
i have model: 
[User] 
   > have one [Patron] 
      > have many [Event] 
          > has one [Game], 
          > has many [Patron] (as attendees)

from [User] i can get [Patron] and [Event] properties
but starting from [Event], i can't get [Game] and [Patron] properties but its ID
for example: 
model.user.get('patron.events.firstObject.date')
(yield) Thu Oct 29 2015 07:00:00 GMT+0700 (WIB)

but this is fail:
model.user.get('patron.events.firstObject.game.showType')
(yield) undefined
