### ISSUE TITLE
Ember-model  compatible with Ember-1.11.1

### ISSUE THREAD

**Issue by leiripmeester** [ebryn/ember-model#419]
I have change the Ember.Model load property.

You acces the meta form  Ember.meta and it return a cashObject.
this object no longer has the property of sersc so i changed it to proto
relationship = meta.dersc[relationshipKey];
relationship = meta.proto[relationshipKey];

**Comment by GavinJoyce** [comment]
Where did you make this change? I've just begun to upgrade from `1.10.1` to `1.11.1` and I'm seeing errors with `hasMany`:

![image](https://cloud.githubusercontent.com/assets/2526/7189270/c0cfee04-e475-11e4-97e0-65a79fef324c.png)

**Comment by GavinJoyce** [comment]
`meta.descs` was removed here: https://github.com/emberjs/ember.js/pull/10323

**Comment by leiripmeester** [comment]
Ruis functioneren: descs to proto



load: function(id, hash) {
    var data = {};
    data[get(this.constructor, 'primaryKey')] = id;
    set(this, '_data', Ember.merge(data, hash));
    this.getWithDefault('_dirtyAttributes', []).clear();

    this._reloadHasManys();

    // eagerly load embedded data
    var relationships = this.constructor._relationships || [], meta = Ember.meta(this), relationshipKey, relationship, relationshipMeta, relationshipData, relationshipType;
    for (var i = 0, l = relationships.length; i < l; i++) {
      relationshipKey = relationships[i];
      relationship = meta.descs[relationshipKey];
      relationshipMeta = relationship.meta();

      if (relationshipMeta.options.embedded) {
        relationshipType = relationshipMeta.type;
        if (typeof relationshipType === "string") {
          relationshipType = Ember.get(Ember.lookup, relationshipType) || this.container.lookupFactory('model:'+ relationshipType);
        }

        relationshipData = data[relationshipKey];
        if (relationshipData) {
          relationshipType.load(relationshipData);
        }
      }
    }
