### ISSUE TITLE
Compatibility with ember-data

### ISSUE THREAD

**Issue by gonvaled** [ebryn/ember-model#420]
Is it possible to have ember-model alongside ember-data? I have been using ember-model in the past for some models, and ember-data for others, without issues, but starting with ember-model@0.0.13 (I think) there seem to be conflicts:

```
Uncaught Error: Assertion Failed: The initializer 'data-adapter' has already been registered
```

**Comment by GavinJoyce** [comment]
You'll need to rename `store` to something like `ember-model-store` and `adapter` to something like `ember-model-adapter` to avoid container naming conflicts with ember-data.

**Comment by rrussell** [comment]
Someone has migrated from `Ember-Data` to `Ember-Model`?

**Comment by GavinJoyce** [comment]
@rrussell I doubt it, we're going from ember-model to ember-data

**Comment by rrussell** [comment]
@GavinJoyce I started working a project with ember-data, but now the CTO wants change to ember-model.
Why migrate to ember-data? Some strong reason or issue with ember-model?

**Comment by spectras** [comment]
Excellent question. I wonder what the status of ember-model is.
I believe `ember-data` is still not very good right now. It's poorly documented, the source is full of todos and fixmes, which is pretty scary, and from what I have seen, it doesn't do much more than `ember-model`, yet it's 3 times bigger.

It would be great to have some input from ember-model maintainers.

**Comment by GavinJoyce** [comment]
It's now possible to use `ember-model` and `ember-data` side by side:

https://github.com/ebryn/ember-model/releases/tag/v2.18.0

**Comment by brandonweiss** [comment]
@GavinJoyce 😍
