### ISSUE TITLE
Assertion Failed: You must use Ember.set() to set the `record` property

### ISSUE THREAD

**Issue by deanmarano** [ebryn/ember-model#426]
I'm getting this error from:

https://github.com/ebryn/ember-model/blob/master/packages/ember-model/lib/model.js#L100

I was able to change this to an Ember.set, and it worked. Not sure how to properly test this though, as I can't reliably reproduce.

**Comment by narkeeso** [comment]
I actually have a PR for this issue. I just haven't had a chance to put together a failing test for it. Looks like others are experiencing the same thing.

https://github.com/ebryn/ember-model/pull/385
