### ISSUE TITLE
Bower doesn't have version 0.0.16 available?

### ISSUE THREAD

**Issue by Shadizzle** [ebryn/ember-model#433]
Is the current release 0.0.15 or 0.0.16? As 0.0.15 doesn't seem to be compatible with > ember 1.1. There seems to be very little information on versioning here on the repo.

0.0.16 is not available in bower. Is this a case of a missing version tag, or is 0.0.16 not yet released?

**Comment by shilov** [comment]
I bumped into this as well. I'm pretty sure it's because there's no git tag for 0.0.16

**Comment by jpweeks** [comment]
@ebryn Can you tag 0.0.16?

**Comment by Shadizzle** [comment]
Just assuming this isn't relevant anymore.
