### ISSUE TITLE
ember-model and ember 2.9.1

### ISSUE THREAD

**Issue by ghost** [ebryn/ember-model#453]
Hi does ember-model work with ember 2.9.1? i get this when trying to use it i get *⠇ BuildingThe Broccoli Plugin: [SourceMapConcat: Concat: Vendor /assets/vendor.js] failed with:
Error: bower_components/ember-model/ember-model.js'*

if its not supported do you intend to support it? 

thanks for your help

**Comment by GavinJoyce** [comment]
@csyleos We successfully using ember-model with ember 2.11.0. Do you still have this problem?
